### ISSUE TITLE
BUG: Failed to copy 'prefetch.js' to dist. Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Kaleidosium** [tyhopp/prpl#70]
I tried running `npm run dev` on a **fresh template** generated by `create-prpl@latest`, but it bugged out, is this related to marked? I tried using an older version `0.3.5` but same issue persists.

```
~
  node -v
v16.17.1
  cd code
~\Code
  npx -y create-prpl@latest

added 40 packages, and audited 41 packages in 4s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> prpl-example-basic@0.0.1 dev
> rm -rf dist && prpl && prpl-server

 [PRPL] Failed to copy 'prefetch.js' to dist. Error: ENOENT: no such file or directory, copyfile 'C:\C:\Users\Kaleidosium\Code\prpl-example-basic\node_modules\@prpl\core\dist\client\prefetch.js' -> 'C:\Users\Kaleidosium\Code\prpl-example-basic\dist\prefetch.js'
 [PRPL] Failed to copy 'prefetch-worker.js' to dist. Error: ENOENT: no such file or directory, copyfile 'C:\C:\Users\Kaleidosium\Code\prpl-example-basic\node_modules\@prpl\core\dist\client\prefetch-worker.js' -> 'C:\Users\Kaleidosium\Code\prpl-example-basic\dist\prefetch-worker.js'
 [PRPL] Failed to copy 'router.js' to dist. Error: ENOENT: no such file or directory, copyfile 'C:\C:\Users\Kaleidosium\Code\prpl-example-basic\node_modules\@prpl\core\dist\client\router.js' -> 'C:\Users\Kaleidosium\Code\prpl-example-basic\dist\router.js'
file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/marked/lib/marked.esm.js:2380
    throw new Error('marked(): input parameter is undefined or null');
          ^

Error: marked(): input parameter is undefined or null
    at marked (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/marked/lib/marked.esm.js:2380:11)
    at transformMarkdown (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/@prpl/core/dist/index.mjs:355:12)
    at interpolatePage (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/@prpl/core/dist/index.mjs:402:39)
    at async interpolateHTML (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/@prpl/core/dist/index.mjs:456:5)
    at async walkSourceTree (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/@prpl/core/dist/index.mjs:488:25)
    at async walkSourceTree (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/@prpl/core/dist/index.mjs:499:21)
    at async interpolate (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/@prpl/core/dist/index.mjs:511:5)
node:child_process:915
    throw err;
    ^

Error: Command failed: npm run dev
    at checkExecSyncError (node:child_process:841:11)
    at Object.execSync (node:child_process:912:15)
    at sh (C:\Users\Kaleidosium\AppData\Local\npm-cache\_npx\aa2ca10baf14b8f3\node_modules\create-prpl\dist\index.cjs:16:19)
    at Object.<anonymous> (C:\Users\Kaleidosium\AppData\Local\npm-cache\_npx\aa2ca10baf14b8f3\node_modules\create-prpl\dist\index.cjs:30:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 8904,
  stdout: null,
  stderr: null
}
~\Code xERROR
  cd .\prpl-example-basic\
~\Code\prpl-example-basic
  npm run dev

> prpl-example-basic@0.0.1 dev
> rm -rf dist && prpl && prpl-server

 [PRPL] Failed to copy 'prefetch.js' to dist. Error: ENOENT: no such file or directory, copyfile 'C:\C:\Users\Kaleidosium\Code\prpl-example-basic\node_modules\@prpl\core\dist\client\prefetch.js' -> 'C:\Users\Kaleidosium\Code\prpl-example-basic\dist\prefetch.js'
 [PRPL] Failed to copy 'prefetch-worker.js' to dist. Error: ENOENT: no such file or directory, copyfile 'C:\C:\Users\Kaleidosium\Code\prpl-example-basic\node_modules\@prpl\core\dist\client\prefetch-worker.js' -> 'C:\Users\Kaleidosium\Code\prpl-example-basic\dist\prefetch-worker.js'
 [PRPL] Failed to copy 'router.js' to dist. Error: ENOENT: no such file or directory, copyfile 'C:\C:\Users\Kaleidosium\Code\prpl-example-basic\node_modules\@prpl\core\dist\client\router.js' -> 'C:\Users\Kaleidosium\Code\prpl-example-basic\dist\router.js'
file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/marked/lib/marked.esm.js:2380
    throw new Error('marked(): input parameter is undefined or null');
          ^

Error: marked(): input parameter is undefined or null
    at marked (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/marked/lib/marked.esm.js:2380:11)
    at transformMarkdown (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/@prpl/core/dist/index.mjs:355:12)
    at interpolatePage (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/@prpl/core/dist/index.mjs:402:39)
    at async interpolateHTML (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/@prpl/core/dist/index.mjs:456:5)
    at async walkSourceTree (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/@prpl/core/dist/index.mjs:488:25)
    at async walkSourceTree (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/@prpl/core/dist/index.mjs:499:21)
    at async interpolate (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/@prpl/core/dist/index.mjs:511:5)
~\Code\prpl-example-basic xERROR
  npm run build

> prpl-example-basic@0.0.1 build
> rm -rf dist && prpl

 [PRPL] Failed to copy 'prefetch.js' to dist. Error: ENOENT: no such file or directory, copyfile 'C:\C:\Users\Kaleidosium\Code\prpl-example-basic\node_modules\@prpl\core\dist\client\prefetch.js' -> 'C:\Users\Kaleidosium\Code\prpl-example-basic\dist\prefetch.js'
 [PRPL] Failed to copy 'prefetch-worker.js' to dist. Error: ENOENT: no such file or directory, copyfile 'C:\C:\Users\Kaleidosium\Code\prpl-example-basic\node_modules\@prpl\core\dist\client\prefetch-worker.js' -> 'C:\Users\Kaleidosium\Code\prpl-example-basic\dist\prefetch-worker.js'
 [PRPL] Failed to copy 'router.js' to dist. Error: ENOENT: no such file or directory, copyfile 'C:\C:\Users\Kaleidosium\Code\prpl-example-basic\node_modules\@prpl\core\dist\client\router.js' -> 'C:\Users\Kaleidosium\Code\prpl-example-basic\dist\router.js'
file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/marked/lib/marked.esm.js:2380
    throw new Error('marked(): input parameter is undefined or null');
          ^

Error: marked(): input parameter is undefined or null
    at marked (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/marked/lib/marked.esm.js:2380:11)
    at transformMarkdown (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/@prpl/core/dist/index.mjs:355:12)
    at interpolatePage (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/@prpl/core/dist/index.mjs:402:39)
    at async interpolateHTML (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/@prpl/core/dist/index.mjs:456:5)
    at async walkSourceTree (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/@prpl/core/dist/index.mjs:488:25)
    at async walkSourceTree (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/@prpl/core/dist/index.mjs:499:21)
    at async interpolate (file:///C:/Users/Kaleidosium/Code/prpl-example-basic/node_modules/@prpl/core/dist/index.mjs:511:5)
```

**Comment by tyhopp** [comment]
Hi @Kaleidosium, thanks for raising this and apologies you ran into this issue. I was able to reproduce the issue by expanding the CI tests to also run on Windows (I use macOS locally and so never encountered this problem).

Will do my best to look into this soon, in the mean time it should work if you run it in [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) on your Windows machine.
